[package]
name = "terrarium-sim"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[lib]

[dependencies]
terrarium-test-spec = { path = "../test-spec" }
thiserror = "2"
uuid = { version = "1", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
wasmtime = "28"
wat = "1"
