ALTER TABLE creatures ADD COLUMN pc INTEGER NOT NULL DEFAULT 0;
ALTER TABLE creatures ADD COLUMN bytecode BLOB;
ALTER TABLE creatures ADD COLUMN stack BLOB NOT NULL DEFAULT x'';

CREATE TABLE IF NOT EXISTS world_tiles (
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    kind INTEGER NOT NULL CHECK (kind IN (1, 3)),
    PRIMARY KEY (x, y)
);
