steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_IMAGE", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE"]

substitutions:
  _IMAGE: us-central1-docker.pkg.dev/PROJECT/terrarium/server:latest

images:
  - $_IMAGE
